const data = [
  {
    title: "Pool 0",
    stacked: "672",
    owed: "183",
    slot: "7",
    link: "DzWPTj1Ym5w5uGoGvdjtRK6GyoG4VpjL8VJhdUcSRfqg",
    reBalance: false,
  },
  {
    title: "Pool 1",
    stacked: "140",
    owed: "0",
    slot: "2",
    link: "45wL48FzxAvMowbHhqwdjRxurDgrMBYRW4G7YqDFFwmW",
    reBalance: false,
  },
  {
    title: "Pool 2",
    stacked: "1917",
    owed: "0",
    slot: "2",
    link: "5Hz47x9T5EpVC6SPK3iwFnAtQvmLuKBf7tMa4z1CTVmS",
    reBalance: true,
  },
  {
    title: "Pool 3",
    stacked: "809",
    owed: "137",
    slot: "3",
    link: "FZvJ1FVepVdQodaSGsi9fmKrYjrv7fHNWFzyRcUM2wsu",
    reBalance: false,
  },
  {
    title: "Pool 4",
    stacked: "456",
    owed: "0",
    slot: "2",
    link: "D83chhV83wr54dJtFYJWnoa7qbpTrHZTjCPbpQHbRmvD",
    reBalance: true,
  },
  {
    title: "Pool 5",
    stacked: "548",
    owed: "99",
    slot: "2",
    link: "GAMzvYjvJitCzrFyLk58uomE6dBEhSzzVfBJvdphTGQs",
    reBalance: true,
  },
  {
    title: "Pool 6",
    stacked: "1922",
    owed: "4",
    slot: "4",
    link: "9ZbRM7cLgEmwSQKWZZTB2tSDU4EFby2U9jkDAkQBmAVC",
    reBalance: true,
  },
  {
    title: "Pool 7",
    stacked: "1077",
    owed: "4",
    slot: "2",
    link: "DrLky4KzLnKUtdcVoYGyKkiSmhWkBt4npANphHf6SEV9",
    reBalance: false,
  },
];

export default data;